{
 "title": "Teleinfo",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "10s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 0 },
   "format": "watt",
   "valueName": "current",
   "targets": [
    {
     "expr": "rate(teleinfo_base[1m]) * 60 * 60"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 0 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    { "expr": "dht11_temperature" }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "dht11_humidity" }
   ]
  },
  {
   "title": "Index de base (en Watt Heure)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "watth" }
   ],
   "targets": [
    { "expr": "teleinfo_base", "legendFormat": "Index de base" },
    {
     "expr": "rate(teleinfo_base[$interval]) * 60 * 60",
     "legendFormat": "index rate"
    }
   ]
  },
  {
   "title": "Puissance apparente (Volt-Ampère)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "voltamp" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(teleinfo_ppap{job=\"teleinfo\"}[$interval])",
     "legendFormat": "Puissance apparente"
    }
   ]
  },
  {
   "title": "Température Humidité",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "quantile_over_time(0.7, dht11_temperature[$interval])",
     "legendFormat": "Température intérieure"
    },
    {
     "expr": "quantile_over_time(0.7, weather_temperature[$interval])",
     "legendFormat": "Température extérieur"
    },
    { "expr": "weather_humidity != 0", "legendFormat": "Humidité extérieure" },
    { "expr": "dht11_humidity", "legendFormat": "Humidité intérieure" }
   ]
  }
 ]
}